version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
    ports:
      - "5000:8080"
    environment:
      - MONGODB_URI=mongodb://127.0.0.1:27017/iot_platform
    depends_on:
      - mongo

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mongo-data: